name: Build Package

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/

    - name: Install packages
      run: |
        echo @b2data:registry=https://npm.pkg.github.com > .npmrc
        echo //npm.pkg.github.com/:_authToken=${{ secrets.REPO_SECRET }} >> .npmrc
        yarn install

    - name: Build Package
      run: |
        yarn gen
        yarn build
    
    - name: Publish NPM Package
      run: |
        npm pack
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
