name: Patch Version

on:
  push:
    branches: [ "main" ]

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/

    - name: Bump version
      run: |
        echo @b2data:registry=https://npm.pkg.github.com > .npmrc
        echo //npm.pkg.github.com/:_authToken=${{ secrets.GITHUB_TOKEN }} >> .npmrc
        git config user.email "noreply@b2data.ton"
        git config user.name "Nikolai Turov"
        npm version patch
        git push
        git push --tags
