name: Publish Package

on:
  push:
    tags: [ "*" ]

jobs:

  build:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
    - uses: actions/checkout@v3
      with:
        node-version: 18
        registry-url: https://npm.pkg.github.com/

    - name: Install packages
      run: yarn install

    - name: Build packages
      run: yarn build

    - name: Publish NPM Package
      run: |
        npm pack
        npm publish
      env:
        NODE_AUTH_TOKEN: ${{secrets.GITHUB_TOKEN}}
